name: unit-tests
on: [push, pull_request]
jobs:
  linux:
    name: linux
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        vim:
          - nightly
          - v9.0.0000
    steps:
      - name: Install packages
        run: |
          sudo apt update
          # install clangd language server
          sudo apt install -y clangd-15
          # install nodejs
          sudo apt install -y curl
          curl -fsSL https://deb.nodesource.com/setup_18.x | sudo bash -
          sudo apt install -y nodejs
          # install the typescript language server
          sudo npm install -g typescript-language-server typescript
          # install the golang language server
          sudo apt install -y golang
          sudo apt install -y gopls
          # install the rust language server
          sudo apt install -y cargo rust-src
          mkdir -p ~/.local/bin
          curl -L https://github.com/rust-lang/rust-analyzer/releases/latest/download/rust-analyzer-x86_64-unknown-linux-gnu.gz | gunzip -c - > ~/.local/bin/rust-analyzer
          chmod +x ~/.local/bin/rust-analyzer
      - name: Setup Vim
        uses: rhysd/action-setup-vim@v1
        id: vim
        with:
          version: ${{ matrix.vim }}
      - name: Checkout LSP plugin Code
        uses: actions/checkout@v4
      - name: Run Tests
        run: |
          uname -a
          ~/.local/bin/rust-analyzer --version
          export VIMPRG=${{ steps.vim.outputs.executable }}
          $VIMPRG --version
          cd test
          ./run_tests.sh
